eureka:
  client:
    service-url:
      defaultZone: http://admin:admin-123@localhost:8761/eureka/
spring:
  application:
    name: springcloud-client
server:
  port: 8082
userinfo:
  username: ailijuan-2020
  password: ailijuan2020
